# -*- coding: utf-8 -*-
"""
Created on Tue Mar 19 17:27:21 2019
https://projecteuler.net/problem=2
@author: matth

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def main():
    print(sum(i for i in bounded_fibonacci(4000000) if i%2 == 0))
    

def bounded_fibonacci(n):
    fibseq = [1,2]
    while fibseq[-1]+fibseq[-2] < n:
        fibseq.append(fibseq[-1]+fibseq[-2])
    return fibseq

#############################

if __name__ == '__main__':
    main()